config-version: 2

name: 'zendesk_source_integration_tests'
version: '0.0.1'

require-dbt-version: [">=0.18.0", "<0.20.0"]
profile: 'integration_tests'

vars:
  zendesk_source:
    group: "{{ ref('group_data') }}"
    organization: "{{ ref('organization_data') }}"
    schedule: "{{ ref('schedule_data') }}"
    ticket: "{{ ref('ticket_data') }}"
    ticket_comment: "{{ ref('ticket_comment_data') }}"
    ticket_field_history: "{{ ref('ticket_field_history_data') }}"
    ticket_schedule: "{{ ref('ticket_schedule_data') }}"
    ticket_tag: "{{ ref('ticket_tag_data') }}"
    user: "{{ snowflake_seed_data('user_data') }}"
    using_sla_policy: True
    using_schedules: True
    
seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  zendesk_source_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    group_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    organization_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    schedule_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        end_time: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        start_time: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        end_time_utc: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        start_time_utc: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created_at: timestamp
    ticket_comment_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        user_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created: timestamp
    ticket_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        due_at: timestamp
        assignee_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        brand_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        external_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        forum_topic_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        group_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        organization_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        problem_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        requester_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        submitter_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        ticket_form_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    ticket_field_history_data:
      +column_types:
        ticket_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        user_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        updated: timestamp
    ticket_schedule_data:
      +column_types:
        ticket_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        schedule_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created_at: timestamp
    user_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        external_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        locale_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        organization_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created_at: timestamp
      +enabled: "{{ true if target.type != 'snowflake' else false }}"
    user_data_snowflake:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        external_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        locale_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        organization_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        created_at: timestamp
      +enabled: "{{ true if target.type == 'snowflake' else false }}"